[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "INEGI-v2"
version = "0.1.0"
description = "LibrerÃ­a de Python para consultar la API de indicadores del INEGI"
requires-python = ">=3.8"
dependencies = [
  "pandas",
  "requests",
  "numpy"
]
